create_project -force -part xczu1cg-sbva484-1-e fpga
add_files -fileset sources_1 defines.v
add_files -fileset sources_1 ../rtl/fpga.v
add_files -fileset sources_1 ../rtl/acc_control.v
add_files -fileset sources_1 ../rtl/complex_mult.v
add_files -fileset sources_1 ../rtl/r22sdf_bf1.v
add_files -fileset sources_1 ../rtl/signed_cast.v
add_files -fileset sources_1 ../rtl/async_true_dual_ram_read_first.v
add_files -fileset sources_1 ../rtl/complex_power.v
add_files -fileset sources_1 ../rtl/r22sdf_bf2.v
add_files -fileset sources_1 ../rtl/single_port_ram_read_first.v
add_files -fileset sources_1 ../rtl/async_true_dual_ram.v
add_files -fileset sources_1 ../rtl/correlation_mults.v
add_files -fileset sources_1 ../rtl/r22sdf_correlator1024.v
add_files -fileset sources_1 ../rtl/skid_buffer.v
add_files -fileset sources_1 ../rtl/async_true_dual_ram_write_first.v
add_files -fileset sources_1 ../rtl/correlator_lane.v
add_files -fileset sources_1 ../rtl/r22sdf_fft1024.v
add_files -fileset sources_1 ../rtl/sync_simple_dual_ram.v
add_files -fileset sources_1 ../rtl/axil_bram_arbiter.v
add_files -fileset sources_1 ../rtl/data_phy.v
add_files -fileset sources_1 ../rtl/r22sdf_fft_stage.v
add_files -fileset sources_1 ../rtl/axil_bram_unbalanced.v
add_files -fileset sources_1 ../rtl/delay.v
add_files -fileset sources_1 ../rtl/r22sdf_twiddle_mult.v
add_files -fileset sources_1 ../rtl/unbalanced_ram.v
add_files -fileset sources_1 ../rtl/axil_bram.v
add_files -fileset sources_1 ../rtl/dsp48_mult.v
add_files -fileset sources_1 ../rtl/resize_data.v
add_files -fileset sources_1 ../rtl/unsign_cast.v
add_files -fileset sources_1 ../rtl/axil_correlator.v
add_files -fileset sources_1 ../rtl/feedback_delay_line.v
add_files -fileset sources_1 ../rtl/rom_bin_init.v
add_files -fileset sources_1 ../rtl/vector_accumulator.v
add_files -fileset sources_1 ../rtl/bitslip_shift.v
add_files -fileset sources_1 ../rtl/s_axil_reg.v
add_files -fileset sources_1 ../rtl/clock_alignment.v
add_files -fileset sources_1 ../rtl/output_clock.v
add_files -fileset sources_1 ../rtl/shift.v
add_files -fileset constrs_1 ../fpga.xdc
source ../ip/mpsoc.tcl
exit
